import './index.scss'
// import './01-simple-scene'
// import './02-character'
// import './03-floor'
// import './04-move-character'
// import './05-follow-character'
// import './06-obstacle'
// import './07-collision'
// import './08-player-health'
// import './09-rotate-player'
import './10-window-resize'
